### ISSUE TITLE
Allow ::alternate on element with display:none

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-braille#105]
The braille CSS specification says about the `::alternate` and `::duplicate` pseudo-elements:
> It is not allowed that several pseudo-elements associated to the same element participate in the same flow (normal or named flow), nor that they participate in the same flow as the element they are associated to.

This means that an element with `display:none` should be able to have an `::alternate` pseudo-element in the normal flow. However the system currently forbids this. Until this is fixed you can use the following workaround:

```css
foo {
   flow: null; /* display: none */
}
foo::alternate {
   content: ...
}
```
