### ISSUE TITLE
"RuntimeException: Error in code" when using -obfl-vertical-position: 25; with a page height of 25 or less

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-mod-braille#153]
Not sure if this counts as a bug, but it would at least be nice if the error message was something more descriptive than "RuntimeException: Error in code".

Relevant XML and CSS (from NLB script, used to show volume number at the bottom of the page):

```xml
<p class="volume"> of </p>
```

```css
.bind::before {
        display: inline;
        content: "Volume " -obfl-evaluate("(round $volume)");
}

.bind {
        display: inline;
        -obfl-vertical-position: 25;
}

.bind::after {
        display: inline;
        content: -obfl-evaluate("(round $volumes)");
        page-break-after: always;
}
```
