### ISSUE TITLE
Multiple flow() functions in same content property with difference ranges can cause problems

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-braille#160]
When a `flow(x)` is combined with a `flow(y, volume)` in the `content` property of a volume area, they can end up in a single `dynamic-sequence`, which results in `flow(x)` not being rendered if `flow(y, volume)` evaluates to nothing.

In some cases this is desired, in some cases not.

An example of where this is desired is in [nlb-default.scss](https://github.com/nlbdev/pipeline/blob/4e5a8ed/modules/nlb/book-to-pef/src/main/resources/css/nlb-default.scss#L784):

```scss
@volume {
    @end {
        content: flow(endnotes-title) flow(endnotes, volume);
    }
}
```
