### ISSUE TITLE
First CSS rule ignored if BOM (byte order mark) present

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-braille#50]
Byte order marks are sometimes used in Windows Unicode files.

The example was:
```css
/* beginning of file, first bytes are EF BB BF */
/* following rule is ignored */
@page {
	size: 28 28;
}
/* rest of CSS file is correctly interpreted */
```
