### ISSUE TITLE
Several @volume rules should be combined

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-braille#73]
For example:

```css
@volume  {
    @begin {
        content: flow(volume-toc);
    }
}

@volume  {
    max-length: 75;
}
```

In this case only second rule survives.

The `@page` rule might have the same issue.
